languageCode = "en-us"
title = "Ecocity Domestic ReManufacturing Upcycling Systems"
theme = "ajonp-hugo-ionic"
description = "Innovations in waste recovery by sustainable meeting the needs of everyday people with everyday products"
metadataformat = "yaml"
canonifyurls = true
disqusShortname = "ecocity"
# enableGitInfo = "true" # you can change this after git init
pygmentsUseClasses = "true"
pygmentsCodeFences = "true"


[author]
  name = "ajonp"
  homepage = "https://www.ecocity.com"


[taxonomies]
  authors = "authors"
  tag = "tags"
  category = "categories"
  languages = "languages"
  
[params]
  toc = "true"
  RSSLink = "/index.xml"
  author = "geog" 
  github = "biomassives" 
  twitter = "ecocity" 
  youtube = "UCGGCCeZqVXZv1CqO7AdOz2A" #channelname
  email = "greg@ecocity.com"
  images = ["https://res.cloudinary.com/ajonp/image/upload/w_500/v1543267002/ajonp-ajonp-com/youtube_banner.png"]
  fb_app_id = "ecocity"

  # Search Only
  [params.algolia]
    appId = "ecocity"
    apiKey = "your_name"
    indexName = "your_name"
  [params.home]
    image = "https://res.cloudinary.com/ajonp/image/upload/v1544021089/ajonp-ajonp-com/Logos/ajonp/welcom_card.png"
    title = "Welcome to Ecocity Remanufacturing and Upcycling Services"
    subtitle = "Journey with us to the other side of broken and antiquated systems."
    showGithub = true
    showTwitter = true
    showYoutube = true

[[menu.main]]
    name = "Home"
    pre = "home"
    weight = -1
    url = "/"
[[menu.main]]
    name = "Lessons"
    pre = "school"
    weight = 100
    url = "/lessons/"
[[menu.main]]
    name = "Blog"
    pre = "book"
    weight = 200
    url = "/blog/"
[[menu.main]]
    name = "Categories"
    pre = "apps"
    weight = 300
    url = "/categories/"
[[menu.main]]
    name = "Tags"
    pre = "pricetag"
    weight = 400
    url = "/tags/"
[[menu.main]]
    name = "Coding Languages"
    pre = "code"
    weight = 500
    url = "/languages/"
